### ISSUE TITLE
 OpenGL Error  when running in linux without qt

### ISSUE THREAD

**Issue by IsaEs** [vicrucann/shader-3dcurve#1]
We compile this project without qt in linux and there is no compiler or linker error.When we try to run we got this error. 

`OpenGL error 'invalid enumerant' at after RenderBin::draw(..) `
`OpenGL error 'invalid enumerant' at after RenderBin::draw(..) `
`OpenGL error 'invalid enumerant' at after RenderBin::draw(..) `
...
`OpenGL error 'invalid enumerant' at after RenderBin::draw(..) `

Windows pops up but there is no shape in the scene.

**Comment by vicrucann** [comment]
This project is supposed to work without Qt (I just removed the Qt dependency from CMake, it was my mistake). Can you tell me: 

* what Linux distro are you in, 
* what OpenSceneGraph version do you use (and whether you can successfully run some basic OSG examples),
* and whether your graphics drivers are up to date.

I might dig up my old Linux machine to see if I can replicate this.

**Comment by IsaEs** [comment]
I missed  the requirements part.I am using ubuntu 14.04 and yes I run some examples and  I work with some other tutorials.But my OpenGL version 3.0  now i am trying to upgrade  OpenGL .i will try to run again. Thank you.
